project_id = "rjlqmfthemfpetpcydog"

[functions.scan-genius-webhook]
verify_jwt = false

[functions.send-parent-notification]
verify_jwt = false

[functions.grade-assignment]
verify_jwt = false

[functions.sync-to-nycologic]
verify_jwt = false

[functions.generate-invite]
verify_jwt = false

[functions.nycologic-webhook]
verify_jwt = false

[functions.sync-student]
verify_jwt = false

[functions.geoblox-sync]
verify_jwt = false

[functions.generate-question-image]
verify_jwt = false